#!/usr/bin/env python3
"""Build single-column reading editions from the two maintained README files."""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build(source, zh):
    text = source
    def stack(match):
        table = match.group()
        if '<img ' not in table:
            return table
        rows = [re.findall(r'<t[dh]\b[^>]*>(.*?)</t[dh]>', row, re.S)
                for row in re.findall(r'<tr>(.*?)</tr>', table, re.S)]
        blocks = []
        if len(rows[0]) == 1:
            blocks = ['<h4>' + rows[0][0] + '</h4>'] + [cell for row in rows[1:] for cell in row]
        else:
            for column in range(len(rows[0])):
                blocks += ['<h4>' + rows[0][column] + '</h4>']
                blocks += [row[column] for row in rows[1:]]
        blocks = [re.sub(r'width="(?:100%|240)"', 'width="100%"', b) for b in blocks]
        return '\n\n'.join(b if b.startswith(('<h4>', '<p>')) else '<p>'+b+'</p>' for b in blocks)
    text = re.sub(r'<table>.*?</table>', stack, text, flags=re.S)
    # The introductory three-GIF row is also stacked on narrow screens.
    def gifs(match):
        rows = [line.strip('|').split('|') for line in match.group().strip().splitlines()]
        if '![' not in match.group():
            return match.group()
        return '\n\n'.join('#### '+title.strip()+'\n\n'+cell.strip()
                            for title,cell in zip(rows[0],rows[2]))+'\n'
    text = re.sub(r'^\|[^\n]+\n\|[ |:-]+\n\|[^\n]+\n', gifs, text, flags=re.M)
    text = re.sub(r'^\*\*\[(?:手机阅读：单列大图版|Reading on a phone\? Open the single-column edition).*?\n\n', '',text, flags=re.M)
    text = text.replace('](./', '](../').replace('href="./', 'href="../').replace('src="./', 'src="../')
    text = text.replace('[English](../README.md)', '[English](./mobile.md)').replace('[简体中文](../README_zh.md)', '[简体中文](./mobile_zh.md)')
    lines = text.splitlines()
    lines[0] += ' · 单列阅读版' if zh else ' · Single-column edition'
    lines.insert(1, '\n[返回并排版首页](../README_zh.md)\n' if zh else '\n[Back to the side-by-side homepage](../README.md)\n')
    return '<!-- Generated by scripts/build_mobile_readme.py; edit README files instead. -->\n'+'\n'.join(lines)+'\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for source,target,zh in [('README.md','docs/mobile.md',False),('README_zh.md','docs/mobile_zh.md',True)]:
        result = build((ROOT/source).read_text(),zh)
        path = ROOT/target
        if args.check:
            if not path.exists() or path.read_text() != result:
                raise SystemExit('Stale mobile edition: '+target)
        else:
            path.write_text(result)
    print('PASS: mobile editions match their README sources')

if __name__ == '__main__':
    main()
